// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: Users.proto

package services

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _users_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on UserScoreRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *UserScoreRequest) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetUsers() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserScoreRequestValidationError{
					field:  fmt.Sprintf("Users[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// UserScoreRequestValidationError is the validation error returned by
// UserScoreRequest.Validate if the designated constraints aren't met.
type UserScoreRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserScoreRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserScoreRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserScoreRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserScoreRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserScoreRequestValidationError) ErrorName() string { return "UserScoreRequestValidationError" }

// Error satisfies the builtin error interface
func (e UserScoreRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserScoreRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserScoreRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserScoreRequestValidationError{}

// Validate checks the field values on UserScoreResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *UserScoreResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetUsers() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserScoreResponseValidationError{
					field:  fmt.Sprintf("Users[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// UserScoreResponseValidationError is the validation error returned by
// UserScoreResponse.Validate if the designated constraints aren't met.
type UserScoreResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserScoreResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserScoreResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserScoreResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserScoreResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserScoreResponseValidationError) ErrorName() string {
	return "UserScoreResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UserScoreResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserScoreResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserScoreResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserScoreResponseValidationError{}
